### PR TITLE
51c false positive undefined label

### PR DESCRIPTION
**Pull request by kpowick**
Note: This PR replaces closed and non-merged PR #92.

This PR corrects issue #51, which was the linter not recognizing program labels that begin with the letters **REM**, e.g. `GOSUB REMAP.DATA:`. This may also correct or be related to issue #86, as valid labels were reported as invalid by that issue as well.

This PR also improves syntax highlighting when **REM** is used as the prefix of a variable name. For example, `DRINK = "Martini"; REMIX = 0` will treat `REMIX` as a variable and not a comment. For REM to identify a comment, the characters **REM** must be followed by one or more spaces, then the actual comment text. e.g. `CRT; REM Display a blank line`.

Finally, this PR standardizes the available Syntax files with regard to the RegExes used to determine comments, trailing comments, and label comments.

### CODE REVIEW

**Comment by itsxallwater** [comment]
I'm going to throw a bit more administrative work at ya, if you don't mind. I just added you as a member to this org which means you won't have to send PRs from your fork anymore, you can branch here locally. I'm doing this because a) you've been super active of late which is very helpful and b) since I've got a few changes to marry up with yours, I figure we might as well be working off the same branch. Easier if we have you join in here.

So, if you don't mind scrapping this PR and instead pushing your changes to this new local branch we've got, https://github.com/mvextensions/mvbasic/tree/kpowick/51b-false-positive-undefined-label, we can PR off of that and be pairing our changes up in the same spot. Enter the administrative work. Sound good to you?

The gist on my changes is `server.ts` contains a lot of references to a local var `currentDocument` which always points to the content of the last document opened. Meanwhile, event handlers like the `hover` are trying to use that to determine what line of code you're hovering on, and that falls over completely if you're looking at any file other than the last one opened. The fix seems to be to switch to a local variable called documents, which is an array of open documents, and to fetch the appropriate document and its contents from there before continuing work. That did well to resolve all of the `split` errors from the `hover` event but there are still some residual errors in the `documentSymbol` section to be dealt with, stemming I think from a local RegEx there trying to build a list of all the "CALL" statements that isn't intelligent enough at the moment to ignore "CALL" inside of comments.

Additionally, the currentDocument -> documents array changes blew the problems out of control for Jan's sample code, so this is in no way shape or form ready for prime time.

**Comment by itsxallwater** [comment]
Some example code I've been hacking at to solve for the CALL detection regex defined on the following line:

https://github.com/mvextensions/mvbasic/blob/d56199977151c6370867883122cdb9094867f86d/server/src/server.ts#L896

```
* N - call a.sub
! O - call a.sub
call a.sub
if true then call a.sub
call a.sub ;* call a.sub
call a.sub ;! call @a.sub
call a.sub ;! "call @a.sub"
call a.sub; print "hello, call a.sub;!" ; call a.sub
```

**Comment by kpowick** [comment]
I'll look at this tomorrow.  No time right now, but I'll close this PR as requested and join-up with the project. Thanks! @itsxallwater

**Comment by kpowick** [comment]
@itsxallwater. I've joined the project, thanks again, and I have that branch (51b...) locally.  I've made some changes to it, but I'm unable to push it back to the project.  Credentials required.

**Comment by itsxallwater** [comment]
What does `git status` show for you and what happens if you `git fetch` and `git checkout kpowick/51b-false-positive-undefined-label`?

**Comment by kpowick** [comment]
Oh, I was able to fetch and check-out locally the branch, no issues.  I just can't push my changes back without permission being denied.  Requested output below:
```
kpowick$ git status
On branch kpowick/51b-false-positive-undefined-label
Your branch is ahead of 'upstream/kpowick/51b-false-positive-undefined-label' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

kpowick$ git push upstream kpowick/51b-false-positive-undefined-label
Username for 'https://github.com': kpowick
Password for 'https://kpowick@github.com':

remote: Permission to mvextensions/mvbasic.git denied to kpowick.
fatal: unable to access 'https://github.com/mvextensions/mvbasic.git/': The requested URL returned error: 403
```

**Comment by itsxallwater** [comment]
Understood and that's weird, shows you as an org member with full repo access now. Can you try a new branch and if that works I'll just move my stuff over?

**Comment by kpowick** [comment]
No joy.  Permission denied when trying to push a new branch to upstream. 
I have to get going, so can revisit tomorrow.

**Comment by itsxallwater** [comment]
Should be all set now, at your convenience!

**Comment by kpowick** [comment]
Success!  Thanks.  I've pushed a commit for RegEx standardization for labels and comments.

**Comment by dthiot** [comment]
I just want to say that Kevin Powick is making an amazing contribution.  Thank you Kevin!

**Comment by kpowick** [comment]
Thanks guys.  

As I get deeper into this project, I hope to offer more comprehensive input and updates. 

Cheers!

**Pull request closed without merging**
