### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by brentlblair**
added logic to add user variables to Intellisense.  I added a setting that defaults to false that can be used to activate this feature.  `MVBasic.userVariablesEnabled`

### CODE REVIEW

**Comment by itsxallwater** [comment]
Will get to this ASAP!

**Comment by itsxallwater** [comment]
@brentlblair I'm good with the changes but can I trouble you to include a docs update with this PR?

**Comment by brentlblair** [comment]
Done

*Brent Blair* <http://www.linkedin.com/in/BrentLBlair>

Vice President of IT
Encompass
Phone 954.474.0300
Fort Lauderdale, FL
<https://www.google.com/maps/place/Encompass+Parts+Distribution/@26.145357,-80.2482168,12.46z/data=!4m5!3m4!1s0x0:0xb2bfe23d3412449!8m2!3d26.0920996!4d-80.2409538>

bblair@encompass.com
encompass.com

**Review by itsxallwater — APPROVED** [review]

**Comment by kpowick** [comment]
Hi All,

I know I haven't been around lately, but I do try to keep tabs on the project. 

I'm a little confused by this new branch called `main`.  What does this represent, and is it necessary?

Shouldn't we really only have `develop`, `master`, and some historical branches from the early days of the project?

**Comment by kpowick** [comment]
Actually, it looks like `master` is gone!  This is highly unusual and not typical branch naming in git projects.

**Comment by itsxallwater** [comment]
Hey Kevin, good to see you again. I flipped us from master to main ahead of GitHub changing the default globally.

You're correct about that not being the standard historically. https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by kpowick** [comment]
Right.  I forgot about that initiative.

**Pull request merged**
