### PR TITLE
Syntax Highlighting Bug Fixes and Features

### PR DESCRIPTION
**Pull request by andrewcole50**
BUG #112

### CODE REVIEW

**Comment by andrewcole50** [comment]
Feature #122. Also accounted for CALL along the same lines.

Added EACH as keyword for OpenQM to account for "FOR EACH"

**Comment by andrewcole50** [comment]
Lastly, changed highlighting MV functions from classes to functions. I find this to be more accurate as, for example, an OCONV(x, y) is most definitely a function and NOT a class and should be highlighted as such.

**Comment by kpowick** [comment]
Hi @andrewcole50,

Nice to see more hands help lighten the load.  Thanks for your work.

Just a FYI.  All pull requests should be for the project's `develop` branch.  Once `develop` achieves stability and includes desired milestones, the changes are pulled into `main` for a new public release of mvExtensions.

A while back, the decision was made for the `main` branch to only represent the current public release of mvExtensions.

Bearing that in mind, it's probably best to set up your own repo that way, so pull requests are from your `develop` branch to the project's `develop` branch.

Again, thanks for tackling some of the open issues.  The more help, the better!

**Comment by itsxallwater** [comment]
Great call @kpowick!

**Comment by andrewcole50** [comment]
@kpowick changed to develop branch.

**Comment by itsxallwater** [comment]
Am I correct in stating that we can close this because you have these changes also incorporated with #148?

**Pull request closed without merging**
