### PR TITLE
Code folding helpers

### PR DESCRIPTION
**Pull request by stuboydl**
Changes:
1. Added "Format Structure" setting (formatStructure) and rule to improve document formatting. This setting helps to produce cleaner formatted code when VSCode's automatic block code folding is used. [The word _structure_ implies structured programming, a common style in MV development - this formatting rule emphasises the structural blocks].

image

VSCode's code folding capabilities are great for helping developers to focus on important parts of code. Swathes of comments or irrelevant code can be hidden away.

Often legacy code has RETURN's indented from the left margin and comments in the left margin. This interferes with clean block structures that VSCode can use for determining code folding regions. The default "MV Basic Format" command doesn't address these issues.

This setting, when combined with the "MVBasic: Indent Comment" setting = "code", will produce formatted code that assists VSCode's automatic block code folding to work cleanly over MV basic code. 

When the format document command is run, the following keywords `(function|program|return|stop|sub|subroutine)` will go to hard left to indicate either the start or end of a code structure block.

folding 1

2. Added MVBasic friendly code folding markers.
Code Folding Markers can be used to fold away irrelevent code or comments which distract from a task. As comments, they may be left in the code without harm.

image

folding 2

### CODE REVIEW

**Comment by itsxallwater** [comment]
Thanks for submitting this! Tagging Pete and I for reviews; we'll look to get this merged in and published here ASAP.

**Review by itsxallwater — APPROVED** [review]

**Comment by itsxallwater** [comment]
Will get a build cut here shortly to use for manual installation and testing

**Comment by itsxallwater** [comment]
@stuboydl @pschellenbach https://zumasyscorp-my.sharepoint.com/:u:/g/personal/mikew_zumasys_com/ESTx12QuQ5BOm535Km3Er28Buswf8laeQPO6nKrwdZLfBQ?e=g7Rc5f you can check out a preview version here.

**Comment by itsxallwater** [comment]
Any reservations about promoting this release? I've not heard of any reported issues.

**Comment by pschellenbach** [comment]
I’m good

**Comment by itsxallwater** [comment]
Not quite so fast I guess, `vsce publish` doesn't like something. Strange since `vsce package` was fine.

image

**Comment by itsxallwater** [comment]
@stuboydl this is finally in production via the marketplace; ultimately came down to adjusting the webpack based bundling of things and making sure the `.vscodeignore` file was keeping all of the node_modules from being included

**Pull request merged**
