### PR TITLE
Update jBASE.tmLanguage.json

### PR DESCRIPTION
**Pull request by andrewcole50**
Added highlighting of jBASE dynamic objects as per #31 

Is this all that was desired from the feature request or are we looking for definitions in jBASELanguage.json as well? I don't mind adding those but am not fully sure as to the syntax for that. I.e. under the key would I put "$split" or "->$split" ? This PR at least gives basic highlighting functionality to all dynamic objects since jBASE follows a predictable method naming schema which makes regex easier. I also named the pattern as a function because at least my theme doesn't highlight methods.

### CODE REVIEW

**Comment by itsxallwater** [comment]
@andrewcole50 same as #139

**Comment by itsxallwater** [comment]
Looks like this one was able to be re-opened unlike #139

**Comment by itsxallwater** [comment]
Looking for work on the language definition as well but don't feel like you need to own this. We at Zumasys, as the vendor, should be able to put time to it! CC @ronaldojr9 :wink:

As far as the syntax, I would think the key would be for `$split` and not `->$split`. I just tested real quick using `$tojson()` and it doesn't seem like the $ was leveraged with the key which could be annoying. If I started typing `tojson` I got the auto-complete. If I started typing `$tojson` I did not.

I ran with this in the language definition but we probably want the `snippet` property to make sure we get the open and closing parenthesis.

``` json
            {
                "key": "$tojson",
                "icon": 3,
                "documentation": "blah blah blah",
                "detail": "$tojson()"
            },
```

pr-143-test

Finding a way to auto complete `->` for jBASE will be handy too. The way I'm thinking about it, I think we want to make sure entry of `->` doesn't just return every single function call or property option since that'd be an intense list. Auto completion of `->` almost needs to be one thing, and subsequent auto completion of the function another. Thinking further on the `->` perhaps that makes sense to do in code rather than in the language definition just because it's really only valid situationally, i.e.:

``` jbase
obj1 = new object("Tour")   ;* We will be adding a few methods to this class shortly
obj1->name = "Socrates"
obj1->city = "Athens"
```

I know I mentioned properties just now but they can probably be a separate thing since that's more about the language server improving intellisense as it parses your code and less about the language definition. There's separate code from @brentlblair in `server.ts` that adds some of that intelligence in already so that'll probably be the place to beef up for that bit.

**Comment by andrewcole50** [comment]
I do agree I think the key should be $split instead of including the arrow. I'm sure the $ is a regex issue I can fix once I fix my compile problems.

As far as an auto complete arrow, I'm not sure that's necessary. I'm mostly a PHP dev and in both VSC and PHPStorm they don't auto complete the arrow (and I type A LOT of arrows in PHP). Once the $ is figured out that will pretty much take care of the autocomplete for jabba functions imo. It will show the entire list once you get to the $ but that's not necessarily a bad thing. For example, when I type "str" in PHP I get a big list of possible functions but if I add an "s" to it I get the two options that start with "strs". I don't think that making a user type "->$t" to thin the list to a few options is unreasonable nor outside of other languages and IDE conventions.

Looking at your image, does whatever theme you're using highlight functions? According to the code in this commit (and my theme of choice) I get $tojson() highlighted. See below
Screen Shot 2021-03-11 at 9 09 02 AM

**Comment by andrewcole50** [comment]
> Looking for work on the language definition as well but don't feel like you need to own this. We at Zumasys, as the vendor, should be able to put time to it! CC @ronaldojr9 😉
> 
Almost forgot about this, I wish I could say I'm contributing for fully altruistic reasons but I'm not. I'm mostly trying to improve the extension so that it makes coding in BASIC more along how I'm used to developing in PHP, Java, etc. Add in that I'm in between a few large projects and the more I put into this the more painless my future projects in BASIC will be. There's also a reason most of my work starts with jBASE and the other flavors are outgrowths of that 😉 Plus in this case at least, I'm already working in these files anyways. Some extra regex isn't that big of a deal.

**Comment by itsxallwater** [comment]
Fair all around. Re: my theme, I've got `Night Owl (No Italics)` running right now and this is what I get:

image

**Comment by itsxallwater** [comment]
Closing this PR so that I can reinitialize develop. @andrewcole50 let me know if you think you'll have an opportunity to pick this work back up. Hope you've been well!

**Comment by stuboydl** [comment]
@andrewcole50 @itsxallwater 
I have a revamped jbase syntax that has:

- general enhancements to jbase syntax handling
- add keywords try/end try/catch/exec/in/throw
- add jabba patterns
- add block comment pattern
- add number pattern
- add pattern for $ifdef $endif etc compiler switch

Can this be re-opened to share it?

**Pull request closed without merging**
