### PR TITLE
Language config

### PR DESCRIPTION
**Pull request by andrewcole50**
Updated version of PR #148 

1. Orphaned snippets are not orphaned anymore!
2. Language snippets are reformatted using verbose snippet syntax

**Issues**
1. Snippets need tested to verify that tab stops work and highlight the placeholder text
2. Snippets need tested to verify new line and tabs work

**Notes**
I still can't seem to build the extension and test server side changes. Idk, what my problem is but it's got me stumped. If the new lines and tab stops don't work I can clean them out and I would propose that we use a snippets.json file for the multi line completions that work for all languages (IF, FOR, maybe READ, etc). There would probably need to be some discussion to figure out which statements needed to be included in that. For any language specific multi line snippets I would say we include their single line alternative in this PR and I may be able to format them such as making them multi line would not be difficult for the end user. Example:
`IF ${1:expression} THEN $2 ${3:then_statements} ${4|END ELSE, ELSE|} ${5:else_statements} $6 ${7|END|}`
$2 and $6 would require the user to press ENTER for multiline or TAB past for singleline while $4 and $7 require one of the selections listed between the pipes or nothing at all.

### CODE REVIEW

**Comment by tcharts-boop** [comment]
@andrewcole50 have you tried adding a reference to the `dom` library in `./client/node_modules/sync-request/lib/FormData.d.ts`?

I had some issues compiling until I added a reference in the file itself.

Should look like this when finished:
image

**Comment by itsxallwater** [comment]
FWIW you no longer need to make that edit so long as you use `develop` as your starting point, thanks to the update to the client's `tsconfig.json` in https://github.com/mvextensions/mvbasic/commit/69dc8e883cb35196db70ef0f1f71aa4f9654bbf7.

May very well be your culprit here @andrewcole50 as it looks like this PR is targeting `main`.

**Comment by andrewcole50** [comment]
@tcharts-boop and @itsxallwater I accidentally pushed this towards main; that's fixed now.

I actually did a fresh clone from the develop branch, made a tiny change, and tried to run with no results again. I also did what you suggested with FormData.d.ts with no luck too. Idk what my issues are here haha. When my tests didn't work, I just kept working on the older project from the main branch just because it was easier than trying to duplicate that work in a new project. There's probably an easier way to do that but I'm not super well versed in git either.

**Comment by itsxallwater** [comment]
Will be a minute before I can pull, test and review this but for grins what is the error you get when you try and build now?

**Comment by andrewcole50** [comment]
> Will be a minute before I can pull, test and review this but for grins what is the error you get when you try and build now?

I actually don't get any errors. It runs and the syntax highlighting works but the server.ts most definitely did not/is not running. No Intellisense suggestions at all unless it's a previously identified variable. 

No rush on pulling and testing! 👍

**Comment by itsxallwater** [comment]
FYI I couldn't `npm run compile` after the initial pull until I re-added "dom" to the `lib` array in the client's `tsconfig.json`. So it still seems like the base of this is maybe pointed at master rather than develop. Weird.

I'm noticing it takes a minute for extensions to activate before I get IntelliSense. Since you're not having any compile or build errors when debugging and you're getting things to pop, curious to ask, how long are you waiting before trying to trigger the IntelliSense? It was probably 30s-1 minute for me.

Looks like newlines and tabs are coming in correctly though!

151-test-1

**Comment by andrewcole50** [comment]
Well at least the new lines and tabs work! I don't know why the placeholders aren't working....

What might be the best course of action for now is to comment out the line that loads the snippets in the server.ts and publish this PR as well as #148 (enables highlighting of jBASE dynamic object methods) as I won't have any time in the near future to work on this. That will allow the release of some syntax fixes/updates, add new languages, and implement the new file naming schema for easier loading in server.ts.

Thoughts?

**Comment by itsxallwater** [comment]
I think so, but I would also want you to re-introduce the snippets contribution in package.json as well. That would effectively keep the new stuff a WIP without impacting anyone using currently, yeah?

**Comment by itsxallwater** [comment]
Closing this PR so that I can reinitialize develop. @andrewcole50 let me know if you think you'll have an opportunity to pick this work back up. Hope you've been well!

**Pull request closed without merging**
