### PR TITLE
Language config

### PR DESCRIPTION
**Pull request by andrewcole50**
Updates language definition files to a naming schema as well as adding snippet data to them. Server then inputs that snippet data if available to IntelliSense. Needs further testing.

### CODE REVIEW

**Comment by andrewcole50** [comment]
Relates to Issue #14

**Comment by itsxallwater** [comment]
Looks like this one was able to be re-opened unlike #139

**Comment by itsxallwater** [comment]
To clean up your `npm run compile` error go ahead and modify your [mvbasic/client/tsconfig.json](https://github.com/mvextensions/mvbasic/blob/develop/client/tsconfig.json) file to be:

``` json
{
  "compilerOptions": {
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "target": "es2019",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": [
      "es2019",
      "dom"
    ],
    "outDir": "out",
    "rootDir": "src",
    "sourceMap": true
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "server"
  ]
}
```

Normally this would've been in `main` but it was changed just after the last deploy and is key in fixing that TypeScript compile issue we hit with one of the project's deps. I think your branch was created off of `main` and so it was missing this update. I patched it locally and was able to then compile, build and run your updates.

Here's a gif of me running and testing from your build. It looks like the consolidation of snippets into the language definition/IntelliSense can work for us! I used jBASE as my `LanguageType` test and both `OPEN` and `READ` filled in per their snippets whereas `FOR` and `OPENSEQ` did not, which was to be expected since those entries in `Lang_jBASE.json` don't have a `snippet` property.

This gets us one step closer--the last piece of the puzzle is the highlighting definition.

image

Side note: installing the GitHub CLI is _neat_--it allowed me to check out your PR via `gh pr checkout 148`.

**Review by itsxallwater — COMMENTED** [review]
I think overall the changes look good. What's your plan for the orphaned snippets--just persist for now?

**Pull request closed without merging**
