### PR TITLE
Add Jbase, OpenQM, D3, UniVerse, and Unidata Language Snippets

### PR DESCRIPTION
**Pull request by andrewcole50**

### CODE REVIEW

**Comment by itsxallwater** [comment]
Work on #16 and #17

**Comment by itsxallwater** [comment]
Thanks Andrew. Confirming receipt, just wanted to let you know it may be a few before you hear back on these but appreciate you getting in!

**Comment by andrewcole50** [comment]
No worries. I was thinking of doing d3, Universe, and Unidata as well as I have a bit of a system set up to scrape the info. Once we verify that the format I provided is at least a good starting point for contributors more familiar with the languages, I'll go ahead and create the snippets file for the mentioned ones. 

I'm SURE there will need to be improvements but my goal here is to get the bones set up so either myself or others can fine tune the snippets later.

**Comment by andrewcole50** [comment]
Work on #18 #19 and #20 

Was inspired and did the setup of remaining snippets. Unidata and Universe will need gone over by someone familiar with those flavors as I have none. But the "skeleton" is set up for each.

**Comment by itsxallwater** [comment]
Hey @andrewcole50 just a quick note to say I haven't lost sight of this, just have been buried elsewhere at the moment. Thank you for the continued work!

**Pull request merged**
